source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '7.0'
pod 'CocoaLumberjack'
pod 'FMDB'
target 'Downloader_Example', :exclusive => true do
  pod 'Downloader', :path => '../'
end

target 'Downloader_Tests', :exclusive => true do
  pod 'Downloader', :path => '../'

  pod 'FBSnapshotTestCase'
end
